### ISSUE TITLE
[HELP]: unable to use TauPlayer/TauRecorder as demonstrated in example

### ISSUE THREAD

**Issue by xuanqi966** [Canardoux/tau#747]
------------

I need Help for :

- Using the API ? Flutter Sound

-------------------------------------
## Here is my question :

Hi, I'm trying to implement my own audio recorder and player and I have been trying to follow the examples given under the example folder of flutter_sound. It seems that the examples given made extensive use of the classes of TauPlayer/TauRecorder, but when I actually try to implement the functionalities in my code I could not find these classes. I've made sure I installed the Flutter Sound package and imported flutter_sound.dart. 
Am I having any misunderstanding in how this package should be used?
Thank you!

**Comment by Larpoux** [comment]
Hi @xuanqi966 

I am really sorry. This is my fault. The default branch on github was the `master` branch instead of `v8`.
(TauPlayer and TauRecorder will be the class to be used in V9.x .But V9.x is not ready to be used. You must use V8.x).

I have just fixed the documentation and the examples.

I hope that you have not lost too much time with my stupidity.
Good luck with your developments with Flutter Sound. 
Do no hesitate to reopen this issue if you have still problems with V8.x

**Comment by xuanqi966** [comment]
> Hi @xuanqi966
> 
> I am really sorry. This is my fault. The default branch on github was the `master` branch instead of `v8`.
> (TauPlayer and TauRecorder will be the class to be used in V9.x .But V9.x is not ready to be used. You must use V8.x).
> 
> I have just fixed the documentation and the examples.
> 
> I hope that you have not lost too much time with my stupidity.
> Good luck with your developments with Flutter Sound.
> Do no hesitate to reopen this issue if you have still problems with V8.x

Resolved, thank you!
