### ISSUE TITLE
[BUG]: SoundRecorderUI and SoundPlayerUI throw various exceptions when 'record' is hit during playback

### ISSUE THREAD

**Issue by jfkominsky** [Canardoux/tau#759]
## Flutter Sound Version : 

- **FULL** or **LITE** flavor ? Full

- **Important**: Result of the command : ```flutter pub deps | grep flutter_sound``` N/A, grep doesn't want to play nice right now for other reasons

----------------------------------------------------------

## Severity

- Crash

--------------------------------------------------------

## Platforms you faced the error 

Android emulator

------------------------------------------------

**Describe the bug**
I'm using a single parent RecorderPlaybackController with a SoundRecorderUI widget and a SoundPlayerUI widget. Each works fine on its own. However, the Recorder widget remains interactable while the player is running, and if you try to start a new recording or delete the existing one while the player is playing, it throws an exception.

**To Reproduce**
Simple, take something like the widget UI demo in the example, record something, then stop the recording and start playback. During playback, start and then attempt to stop or pause or delete the recording, and an assertionerror exception arises:
```
__playState != _PlayState.playing && __playState != _PlayState.paused
```
This assertion is on line 392 of sound_player_ui.dart, it's part of "playbackEnabled".

The app crashes altogether and must be reset.

Most likely the simplest fix will be to disable the recorder UI during playback, but I am not confident enough in my understanding of how the RecorderPlaybackController is put together to hack something together.
----------------------------------------------

**Comment by Larpoux** [comment]
Actually, the Flutter Sound UI Widgets are not maintained by anybody.
This is really bad. I kept those 3 Widgets in the current Flutter Sound code, because I hope that someone (not me !)
will maintain them, one day.
Those widgets was coded by @bsutton, but he does not want to maintain his code 👎 

I know that those Widgets are buggy. If you can suggest some fix, go ahead. You cannot break something which is already broken. Please, do intensive tests and do a Pull Request. It would be great if we get a new contributor for that.

**Comment by jfkominsky** [comment]
PR 763 was my fix for the basic bug. Still issues with the widget UI overall, but this bug has been fixed.

**Comment by Larpoux** [comment]
Hi @jfkominsky ,

Thank you so much for your contribution. I am very glad that someone works on the UI Widget.

I have a problem when I run the Widget UI Demo : 
very often I get an assertion error during the recorder opening : 
"assert(findSession(aSession) == -1);" in flutter_sound_recorder_plateform_interface.dart line 124

It seems that we try to open several times the recorder, and actually the `_openAudioSession()` procedure is badly protected by an assert instead of throwing an exception.

I am currently working on a future V9 and I will fix that in this Version.
But we must also understand why the Demo open several times the recorder, and fix that.

Of course there is no obligation, but if someone (you? 😉  ) can look to that it would be great.

**Comment by Larpoux** [comment]
There is also a pending issue for a long time which was entered by a spanish man : 

The UI Widgets shows english texts, like "The recorder is stopped" , ...
This is not good to have english in our UI.

Probably better to be able to parameterize these texts, or replace them by icons, or remove them completely and put instead a real progress bar for the DB Peak Level, or ...

If you want to work on this issue, you may do what you want : you are the boss now 😉

**Comment by jfkominsky** [comment]
About opening multiple recorders: As far as I can tell that is probably a problem with the demo rather than the UI widget itself, because the only time a recorder is opened by the UI widget itself is during initState. I've put the widget in another app and it's not having any problems. The demo for the widget is a hot mess and I'm sorry to say I really don't have time to replace it.

About the text thing: Yeah, that should be replaced by something like a DB peak meter and a timer, and I will probably need to do that for my own project at some point because I do want to use the widget (it's still easier than trying to make one of my own from scratch). That, playback control in the player widget (i.e., being able to do anything with the slider), and maybe even something that lets you splice the recording a little if it's in the same RecorderPlaybackController are things I'd like to poke eventually, but it might be a while before I have time.

**Comment by Larpoux** [comment]
Flutter Sound 8.3.11 is released with your Pull Request integrated inside.
